### ISSUE TITLE
Not working in expo

### ISSUE THREAD

**Issue by kevin-bache** [alex-melnyk/slide-presenter#1]
Expo link in the readme is not working. Seems to be a permission issue

![img_43f449b22769-1](https://user-images.githubusercontent.com/3761722/39718923-b62f335a-5205-11e8-94ce-d5387c4c91f5.jpeg)

**Comment by alex-melnyk** [comment]
Strange thing, but every project which I try to open show me the same message.

But in the setting all projects are opened.

With best regards,
Alex Melnyk

**Comment by alex-melnyk** [comment]
You may clone the project and run locally, it might work.
