### ISSUE TITLE
Issue running project after following instructions

### ISSUE THREAD

**Issue by famoustunde** [alex-melnyk/slide-presenter#2]
Please can you assist running this project on Android without using Expo ? 
would be nice to have a readme or detailed process on how to get started with your project. 
Thanks

**Comment by alex-melnyk** [comment]
Ok, will do

With best regards,
Alex Melnyk

**Comment by alex-melnyk** [comment]
I updated README file, but in your case, you need to run `yarn run eject` command, it will extract iOS and Android projects, after that, you will see them in the root directory and you can open it like a usual project.

**Comment by famoustunde** [comment]
Okay, no problem. Thanks for updating the readme file, i think i will just go with the Expo CLI because right now after running yarn run eject, i am getting an error. Right now, followed all the read me, and run yarn run eject, but i am getting : 
"The ExpoSDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project."
